Protonu pytorch fusion
bertmaher/pytorch pull request #85
Opened 2020-02-03 18:32 UTC by protonu

2020-02-03 21:14 UTC, bertmaher commented on torch/csrc/jit/tensorexpr/expr.cpp
> +  return Intrinsics::make(kNeg, v);
`neg` in the current fuser is `-${0}`, and llvm doesn't appear to have an intrinsic for this...

2020-02-06 04:42 UTC, bertmaher requested changes
@protonu are you going to finish this?  It looks pretty reasonable to me, except for the things that shouldn't be intrinsics (relu, neg, sigmoid).  Basically only things that are provided by the platform std library and don't have a reasonable arithmetic implementation should be intrinsics.

2020-02-06 04:42 UTC, bertmaher commented on torch/csrc/jit/tensorexpr/expr.cpp
> +  return Intrinsics::make(kNeg, v);
`neg` shouldn't be an intrinsic, IMO.

2020-02-06 04:42 UTC, bertmaher commented on torch/csrc/jit/tensorexpr/expr.cpp
> +Expr relu(const Expr& v) {
`relu` isn't an intrinsic, it's `${0} < 0 ? 0.f : ${0}`  (or, `max(${0}, 0.0`, since we have `max` in our DSL).

2020-02-06 04:42 UTC, bertmaher commented on torch/csrc/jit/tensorexpr/expr.cpp
> +Expr sigmoid(const Expr& v) {
`sigmoid` isn't an intrinsic, it's implemented as `1.f / (1.f + expf(-${0}))", "1. / (1. + exp(-${0}))`

2020-02-06 04:45 UTC, protonu commented
I am working on redoing this PR. I ran in to some build/linker/merge issues.

2020-02-06 08:24 UTC, protonu commented
I'll close this PR soon.

2020-02-06 19:20 UTC, closed without merging